const body = document.querySelector('body');

function startGame() {
    body.innerHTML = `
        <h1 id="gameTitle">-BATTLESHIP!-</h1>
    <div id="versusArea">
        <div class="mapArea" id="playerBattleGround">
            <div class="playerCell" id="0"></div>
            <div class="playerCell" id="1"></div>
            <div class="playerCell" id="2"></div>
            <div class="playerCell" id="3"></div>
            <div class="playerCell" id="4"></div>
            <div class="playerCell" id="5"></div>
            <div class="playerCell" id="6"></div>
            <div class="playerCell" id="7"></div>
            <div class="playerCell" id="8"></div>
            <div class="playerCell" id="9"></div>
            <div class="playerCell" id="10"></div>
            <div class="playerCell" id="11"></div>
            <div class="playerCell" id="12"></div>
            <div class="playerCell" id="13"></div>
            <div class="playerCell" id="14"></div>
            <div class="playerCell" id="15"></div>
            <div class="playerCell" id="16"></div>
            <div class="playerCell" id="17"></div>
            <div class="playerCell" id="18"></div>
            <div class="playerCell" id="19"></div>
            <div class="playerCell" id="20"></div>
            <div class="playerCell" id="21"></div>
            <div class="playerCell" id="22"></div>
            <div class="playerCell" id="23"></div>
            <div class="playerCell" id="24"></div>
            <div class="playerCell" id="25"></div>
            <div class="playerCell" id="26"></div>
            <div class="playerCell" id="27"></div>
            <div class="playerCell" id="28"></div>
            <div class="playerCell" id="29"></div>
            <div class="playerCell" id="30"></div>
            <div class="playerCell" id="31"></div>
            <div class="playerCell" id="32"></div>
            <div class="playerCell" id="33"></div>
            <div class="playerCell" id="34"></div>
            <div class="playerCell" id="35"></div>
            <div class="playerCell" id="36"></div>
            <div class="playerCell" id="37"></div>
            <div class="playerCell" id="38"></div>
            <div class="playerCell" id="39"></div>
            <div class="playerCell" id="40"></div>
            <div class="playerCell" id="41"></div>
            <div class="playerCell" id="42"></div>
            <div class="playerCell" id="43"></div>
            <div class="playerCell" id="44"></div>
            <div class="playerCell" id="45"></div>
            <div class="playerCell" id="46"></div>
            <div class="playerCell" id="47"></div>
            <div class="playerCell" id="48"></div>
            <div class="playerCell" id="49"></div>
            <div class="playerCell" id="50"></div>
            <div class="playerCell" id="51"></div>
            <div class="playerCell" id="52"></div>
            <div class="playerCell" id="53"></div>
            <div class="playerCell" id="54"></div>
            <div class="playerCell" id="55"></div>
            <div class="playerCell" id="56"></div>
            <div class="playerCell" id="57"></div>
            <div class="playerCell" id="58"></div>
            <div class="playerCell" id="59"></div>
            <div class="playerCell" id="60"></div>
            <div class="playerCell" id="61"></div>
            <div class="playerCell" id="62"></div>
            <div class="playerCell" id="63"></div>
            <div class="playerCell" id="64"></div>
            <div class="playerCell" id="65"></div>
            <div class="playerCell" id="66"></div>
            <div class="playerCell" id="67"></div>
            <div class="playerCell" id="68"></div>
            <div class="playerCell" id="69"></div>
            <div class="playerCell" id="70"></div>
            <div class="playerCell" id="71"></div>
            <div class="playerCell" id="72"></div>
            <div class="playerCell" id="73"></div>
            <div class="playerCell" id="74"></div>
            <div class="playerCell" id="75"></div>
            <div class="playerCell" id="76"></div>
            <div class="playerCell" id="77"></div>
            <div class="playerCell" id="78"></div>
            <div class="playerCell" id="79"></div>
            <div class="playerCell" id="80"></div>
            <div class="playerCell" id="81"></div>
            <div class="playerCell" id="82"></div>
            <div class="playerCell" id="83"></div>
            <div class="playerCell" id="84"></div>
            <div class="playerCell" id="85"></div>
            <div class="playerCell" id="86"></div>
            <div class="playerCell" id="87"></div>
            <div class="playerCell" id="88"></div>
            <div class="playerCell" id="89"></div>
            <div class="playerCell" id="90"></div>
            <div class="playerCell" id="91"></div>
            <div class="playerCell" id="92"></div>
            <div class="playerCell" id="93"></div>
            <div class="playerCell" id="94"></div>
            <div class="playerCell" id="95"></div>
            <div class="playerCell" id="96"></div>
            <div class="playerCell" id="97"></div>
            <div class="playerCell" id="98"></div>
            <div class="playerCell" id="99"></div>
        </div>
        <div class="mapArea" id="CPUBattleGround">
            <div class="CPUCELL" id="0">
                <img src="./hit.png" alt="">
            </div>
            <div class="CPUCell" id="1"><img src="cross.svg" alt=""></div>
            <div class="CPUCell" id="2"><img src="./crosshair.svg" alt=""></div>
            <div class="CPUCell" id="3"></div>
            <div class="CPUCell" id="4"></div>
            <div class="CPUCell" id="5"></div>
            <div class="CPUCell" id="6"></div>
            <div class="CPUCell" id="7"></div>
            <div class="CPUCell" id="8"></div>
            <div class="CPUCell" id="9"></div>
            <div class="CPUCell" id="10"></div>
            <div class="CPUCell" id="11"></div>
            <div class="CPUCell" id="12"></div>
            <div class="CPUCell" id="13"></div>
            <div class="CPUCell" id="14"></div>
            <div class="CPUCell" id="15"></div>
            <div class="CPUCell" id="16"></div>
            <div class="CPUCell" id="17"></div>
            <div class="CPUCell" id="18"></div>
            <div class="CPUCell" id="19"></div>
            <div class="CPUCell" id="20"></div>
            <div class="CPUCell" id="21"></div>
            <div class="CPUCell" id="22"></div>
            <div class="CPUCell" id="23"></div>
            <div class="CPUCell" id="24"></div>
            <div class="CPUCell" id="25"></div>
            <div class="CPUCell" id="26"></div>
            <div class="CPUCell" id="27"></div>
            <div class="CPUCell" id="28"></div>
            <div class="CPUCell" id="29"></div>
            <div class="CPUCell" id="30"></div>
            <div class="CPUCell" id="31"></div>
            <div class="CPUCell" id="32"></div>
            <div class="CPUCell" id="33"></div>
            <div class="CPUCell" id="34"></div>
            <div class="CPUCell" id="35"></div>
            <div class="CPUCell" id="36"></div>
            <div class="CPUCell" id="37"></div>
            <div class="CPUCell" id="38"></div>
            <div class="CPUCell" id="39"></div>
            <div class="CPUCell" id="40"></div>
            <div class="CPUCell" id="41"></div>
            <div class="CPUCell" id="42"></div>
            <div class="CPUCell" id="43"></div>
            <div class="CPUCell" id="44"></div>
            <div class="CPUCell" id="45"></div>
            <div class="CPUCell" id="46"></div>
            <div class="CPUCell" id="47"></div>
            <div class="CPUCell" id="48"></div>
            <div class="CPUCell" id="49"></div>
            <div class="CPUCell" id="50"></div>
            <div class="CPUCell" id="51"></div>
            <div class="CPUCell" id="52"></div>
            <div class="CPUCell" id="53"></div>
            <div class="CPUCell" id="54"></div>
            <div class="CPUCell" id="55"></div>
            <div class="CPUCell" id="56"></div>
            <div class="CPUCell" id="57"></div>
            <div class="CPUCell" id="58"></div>
            <div class="CPUCell" id="59"></div>
            <div class="CPUCell" id="60"></div>
            <div class="CPUCell" id="61"></div>
            <div class="CPUCell" id="62"></div>
            <div class="CPUCell" id="63"></div>
            <div class="CPUCell" id="64"></div>
            <div class="CPUCell" id="65"></div>
            <div class="CPUCell" id="66"></div>
            <div class="CPUCell" id="67"></div>
            <div class="CPUCell" id="68"></div>
            <div class="CPUCell" id="69"></div>
            <div class="CPUCell" id="70"></div>
            <div class="CPUCell" id="71"></div>
            <div class="CPUCell" id="72"></div>
            <div class="CPUCell" id="73"></div>
            <div class="CPUCell" id="74"></div>
            <div class="CPUCell" id="75"></div>
            <div class="CPUCell" id="76"></div>
            <div class="CPUCell" id="77"></div>
            <div class="CPUCell" id="78"></div>
            <div class="CPUCell" id="79"></div>
            <div class="CPUCell" id="80"></div>
            <div class="CPUCell" id="81"></div>
            <div class="CPUCell" id="82"></div>
            <div class="CPUCell" id="83"></div>
            <div class="CPUCell" id="84"></div>
            <div class="CPUCell" id="85"></div>
            <div class="CPUCell" id="86"></div>
            <div class="CPUCell" id="87"></div>
            <div class="CPUCell" id="88"></div>
            <div class="CPUCell" id="89"></div>
            <div class="CPUCell" id="90"></div>
            <div class="CPUCell" id="91"></div>
            <div class="CPUCell" id="92"></div>
            <div class="CPUCell" id="93"></div>
            <div class="CPUCell" id="94"></div>
            <div class="CPUCell" id="95"></div>
            <div class="CPUCell" id="96"></div>
            <div class="CPUCell" id="97"></div>
            <div class="CPUCell" id="98"></div>
            <div class="CPUCell" id="99"></div>
        </div>
    </div>
    <div id="scoreCard">
        <div id="playerShipsRemaining"><h5>Player Ships <br> Remaining: 0</h5></div>
        <div id="CPUShipsRemaining"><h5>CPU Ships <br> Remaining: 0</h5></div>
        <div id="turnIndicator">
            <h4>YOUR TURN!</h4>
        </div>
    </div>
    `;
}

export { startGame as gameloop};